export type FootballUniverse = 'college' | 'nfl'
export type FootballPosition = 'QB' | 'WR' | 'RB' | 'TE'

export interface FootballPlayer {
  id: string
  name: string
  universe: FootballUniverse
  position: FootballPosition
  organization: string
  secondary: string
  oracleRank: number | null
  researchScore: number | null
  evidenceState: 'completed_season' | 'feature_feed_pending'
  summary: string
}

export const FOOTBALL_POSITIONS = ['QB', 'WR', 'RB', 'TE'] as const

export const NFL_ORACLE_POSITION_UNIVERSE_SIZE: Readonly<Record<FootballPosition, number>> = {
  QB: 115,
  WR: 387,
  RB: 213,
  TE: 193,
}

export const footballPlayers: readonly FootballPlayer[] = [
  {
    id: 'nfl-jared-goff',
    name: 'Jared Goff',
    universe: 'nfl',
    position: 'QB',
    organization: 'DET',
    secondary: 'Age 31.9',
    oracleRank: 1,
    researchScore: 0.74516,
    evidenceState: 'completed_season',
    summary: 'The locked baseline places his completed-season opportunity and contribution profile first in the current QB research cohort.',
  },
  {
    id: 'nfl-drake-maye',
    name: 'Drake Maye',
    universe: 'nfl',
    position: 'QB',
    organization: 'NE',
    secondary: 'Age 24.0',
    oracleRank: 2,
    researchScore: 0.73581,
    evidenceState: 'completed_season',
    summary: 'A young age curve and strong completed-season signal put him near the top of the internal QB ordering.',
  },
  {
    id: 'nfl-matthew-stafford',
    name: 'Matthew Stafford',
    universe: 'nfl',
    position: 'QB',
    organization: 'LAR',
    secondary: 'Age 38.6',
    oracleRank: 3,
    researchScore: 0.702044,
    evidenceState: 'completed_season',
    summary: 'The short-window production signal remains strong, while age and durability should be treated as separate dynasty-market risks.',
  },
  {
    id: 'nfl-patrick-mahomes',
    name: 'Patrick Mahomes',
    universe: 'nfl',
    position: 'QB',
    organization: 'KC',
    secondary: 'Age 31.0',
    oracleRank: 4,
    researchScore: 0.670077,
    evidenceState: 'completed_season',
    summary: 'A high-confidence established profile; market comparison should be interpreted within QB and league format only.',
  },
  {
    id: 'nfl-jamarr-chase',
    name: "Ja'Marr Chase",
    universe: 'nfl',
    position: 'WR',
    organization: 'CIN',
    secondary: 'Age 26.5',
    oracleRank: 1,
    researchScore: 0.851976,
    evidenceState: 'completed_season',
    summary: 'The strongest locked WR score in the preseason checkpoint, supported by mature opportunity and contribution evidence.',
  },
  {
    id: 'nfl-jaxon-smith-njigba',
    name: 'Jaxon Smith-Njigba',
    universe: 'nfl',
    position: 'WR',
    organization: 'SEA',
    secondary: 'Age 24.5',
    oracleRank: 2,
    researchScore: 0.802562,
    evidenceState: 'completed_season',
    summary: 'A high internal rank paired with a favorable age curve makes him an important market-consensus comparison candidate.',
  },
  {
    id: 'nfl-amon-ra-st-brown',
    name: 'Amon-Ra St. Brown',
    universe: 'nfl',
    position: 'WR',
    organization: 'DET',
    secondary: 'Age 26.9',
    oracleRank: 3,
    researchScore: 0.739435,
    evidenceState: 'completed_season',
    summary: 'A stable top-tier WR signal whose eventual edge label depends on a rights-attested same-format market snapshot.',
  },
  {
    id: 'nfl-puka-nacua',
    name: 'Puka Nacua',
    universe: 'nfl',
    position: 'WR',
    organization: 'LAR',
    secondary: 'Age 25.3',
    oracleRank: 4,
    researchScore: 0.720299,
    evidenceState: 'completed_season',
    summary: 'A strong internal impact ordering with enough age runway to remain relevant across dynasty and two-year research horizons.',
  },
  {
    id: 'nfl-bijan-robinson',
    name: 'Bijan Robinson',
    universe: 'nfl',
    position: 'RB',
    organization: 'ATL',
    secondary: 'Age 24.6',
    oracleRank: 1,
    researchScore: 0.714432,
    evidenceState: 'completed_season',
    summary: 'The leading RB in the locked model checkpoint, with the comparison constrained to position rank rather than raw market value.',
  },
  {
    id: 'nfl-jahmyr-gibbs',
    name: 'Jahmyr Gibbs',
    universe: 'nfl',
    position: 'RB',
    organization: 'DET',
    secondary: 'Age 24.5',
    oracleRank: 2,
    researchScore: 0.635072,
    evidenceState: 'completed_season',
    summary: 'A young, high-ranking RB profile that should be evaluated against an equally configured market universe.',
  },
  {
    id: 'nfl-christian-mccaffrey',
    name: 'Christian McCaffrey',
    universe: 'nfl',
    position: 'RB',
    organization: 'SF',
    secondary: 'Age 30.2',
    oracleRank: 3,
    researchScore: 0.615953,
    evidenceState: 'completed_season',
    summary: 'Current impact evidence remains strong, while dynasty-market age discounting may create a useful horizon-specific disagreement.',
  },
  {
    id: 'nfl-jonathan-taylor',
    name: 'Jonathan Taylor',
    universe: 'nfl',
    position: 'RB',
    organization: 'IND',
    secondary: 'Age 27.6',
    oracleRank: 4,
    researchScore: 0.571106,
    evidenceState: 'completed_season',
    summary: 'A mature RB signal where near-term impact and long-term market value should not be treated as the same target.',
  },
  {
    id: 'nfl-trey-mcbride',
    name: 'Trey McBride',
    universe: 'nfl',
    position: 'TE',
    organization: 'ARI',
    secondary: 'Age 26.8',
    oracleRank: 1,
    researchScore: 0.943209,
    evidenceState: 'completed_season',
    summary: 'The strongest position-relative score in the locked NFL checkpoint and a natural anchor for TE-premium comparisons.',
  },
  {
    id: 'nfl-colston-loveland',
    name: 'Colston Loveland',
    universe: 'nfl',
    position: 'TE',
    organization: 'CHI',
    secondary: 'Age 22.4',
    oracleRank: 2,
    researchScore: 0.735869,
    evidenceState: 'completed_season',
    summary: 'A young TE with a high internal position rank; market comparisons must preserve the selected TE-premium setting.',
  },
  {
    id: 'nfl-kyle-pitts',
    name: 'Kyle Pitts',
    universe: 'nfl',
    position: 'TE',
    organization: 'ATL',
    secondary: 'Age 25.9',
    oracleRank: 3,
    researchScore: 0.641563,
    evidenceState: 'completed_season',
    summary: 'A useful disagreement candidate once licensed market ranks are loaded, especially across different TE-premium assumptions.',
  },
  {
    id: 'nfl-tyler-warren',
    name: 'Tyler Warren',
    universe: 'nfl',
    position: 'TE',
    organization: 'IND',
    secondary: 'Age 24.3',
    oracleRank: 4,
    researchScore: 0.618289,
    evidenceState: 'completed_season',
    summary: 'A young TE profile retained near the top of the internal cohort while external market access remains link-only.',
  },
  {
    id: 'college-arch-manning',
    name: 'Arch Manning',
    universe: 'college',
    position: 'QB',
    organization: 'Texas',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Candidate retained for the college identity bridge. No Oracle rank is released until the CFBD feature feed and target support are locked.',
  },
  {
    id: 'college-dante-moore',
    name: 'Dante Moore',
    universe: 'college',
    position: 'QB',
    organization: 'Oregon',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'College candidate only; production, age, and schedule-adjusted features remain fail-closed pending a licensed feed.',
  },
  {
    id: 'college-julian-sayin',
    name: 'Julian Sayin',
    universe: 'college',
    position: 'QB',
    organization: 'Ohio State',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Included in the broad college watch universe, with model output withheld until feature coverage is complete.',
  },
  {
    id: 'college-lanorris-sellers',
    name: 'LaNorris Sellers',
    universe: 'college',
    position: 'QB',
    organization: 'South Carolina',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'A tracked college quarterback identity; no cross-scale comparison is made between devy values and NFL dynasty values.',
  },
  {
    id: 'college-jeremiah-smith',
    name: 'Jeremiah Smith',
    universe: 'college',
    position: 'WR',
    organization: 'Ohio State',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Priority identity coverage for the future college model; statistical feature ingestion is not yet activated.',
  },
  {
    id: 'college-cam-coleman',
    name: 'Cam Coleman',
    universe: 'college',
    position: 'WR',
    organization: 'Texas',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Tracked in the college candidate universe with all Oracle outputs withheld pending feature and identity validation.',
  },
  {
    id: 'college-malachi-toney',
    name: 'Malachi Toney',
    universe: 'college',
    position: 'WR',
    organization: 'Miami',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'A college receiver candidate whose age-adjusted production features will be added after CFBD access is configured.',
  },
  {
    id: 'college-dakorien-moore',
    name: 'Dakorien Moore',
    universe: 'college',
    position: 'WR',
    organization: 'Oregon',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Visible for identity and coverage planning only; no market value or unsupported model score is reproduced.',
  },
  {
    id: 'college-kewan-lacy',
    name: 'Kewan Lacy',
    universe: 'college',
    position: 'RB',
    organization: 'Ole Miss',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Tracked for the college RB cohort while usage, receiving, and age-adjusted production features remain pending.',
  },
  {
    id: 'college-bo-jackson',
    name: 'Bo Jackson',
    universe: 'college',
    position: 'RB',
    organization: 'Ohio State',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Candidate identity is present, but the Oracle will not infer a rank from market attention alone.',
  },
  {
    id: 'college-ahmad-hardy',
    name: 'Ahmad Hardy',
    universe: 'college',
    position: 'RB',
    organization: 'Missouri',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Included for future feature coverage; a rights-attested market rank can be imported but does not become an Oracle score.',
  },
  {
    id: 'college-jadan-baugh',
    name: 'Jadan Baugh',
    universe: 'college',
    position: 'RB',
    organization: 'Florida',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'College watch-universe record only; opportunity and contribution features are not yet licensed and locked.',
  },
  {
    id: 'college-treydez-green',
    name: "Trey'Dez Green",
    universe: 'college',
    position: 'TE',
    organization: 'LSU',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'A college TE identity retained for feature development; eventual comparisons must preserve TE-premium settings.',
  },
  {
    id: 'college-luke-reynolds',
    name: 'Luke Reynolds',
    universe: 'college',
    position: 'TE',
    organization: 'Virginia Tech',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Visible in the developmental universe while the college receiving-opportunity model remains under construction.',
  },
  {
    id: 'college-terrance-carter',
    name: 'Terrance Carter Jr.',
    universe: 'college',
    position: 'TE',
    organization: 'Texas Tech',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'Candidate coverage only; no value is copied from devy boards and no probability claim is made.',
  },
  {
    id: 'college-luke-hasz',
    name: 'Luke Hasz',
    universe: 'college',
    position: 'TE',
    organization: 'Ole Miss',
    secondary: 'Developmental universe',
    oracleRank: null,
    researchScore: null,
    evidenceState: 'feature_feed_pending',
    summary: 'A tracked college TE identity with model and edge output withheld until the source and target gates pass.',
  },
]
